# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run module verification in dependency order"
  lane :test do
    workspace = "Ditto3.xcworkspace"
    shared_derived_data_path = "build/DerivedData"
    run_tests(
      workspace: workspace,
      scheme: "Platform",
      derived_data_path: shared_derived_data_path,
      clean: true
    )
    run_tests(
      workspace: workspace,
      scheme: "Core",
      derived_data_path: shared_derived_data_path,
      clean: true
    )
  end
end
