import ProjectDescription
import ProjectDescriptionHelpers

let workspace = Workspace(
  name: AppConfig.projectName,
  projects: [
    "App",
    "Core",
    "Feature",
    "Platform",
  ],
  generationOptions: .options(
    // But not working in tuist 4.150.0.
    // https://github.com/tuist/tuist/issues/8501
    autogeneratedWorkspaceSchemes: .disabled
  )
)
